### ISSUE TITLE
Cottontail DB embedded adapter does not respect port specified in UI

### ISSUE THREAD

**Issue by silvanheller** [polypheny/Polypheny-DB#389]
To reproduce: 
- Start something on Port 1865
- Try to start a cottontail embedded adapter on any port (e.g. 1866) via the UI
- Watch as the log says:
```
Caused by: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:1865
	at io.grpc.netty.shaded.io.grpc.netty.NettyServer.start(NettyServer.java:328) ~[polypheny-db.jar:?]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:183) ~[polypheny-db.jar:?]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:92) ~[polypheny-db.jar:?]
	at org.vitrivr.cottontail.server.grpc.CottontailGrpcServer.start(CottontailGrpcServer.kt:57) ~[polypheny-db.jar:?]
	at org.vitrivr.cottontail.CottontailKt.embedded(Cottontail.kt:203) ~[polypheny-db.jar:?]
	at org.polypheny.db.adapter.cottontail.CottontailStore.<init>(CottontailStore.java:148) ~[polypheny-db.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.polypheny.db.adapter.AdapterManager.addAdapter(AdapterManager.java:225) ~[polypheny-db.jar:?]
	at org.polypheny.db.ddl.DdlManagerImpl.addAdapter(DdlManagerImpl.java:215) ~[polypheny-db.jar:?]
	at org.polypheny.db.sql.sql.ddl.SqlAlterAdaptersAdd.execute(SqlAlterAdaptersAdd.java:93) ~[polypheny-db.jar:?]
	at org.polypheny.db.processing.Processor.getResult(Processor.java:75) ~[polypheny-db.jar:?]
	at org.polypheny.db.processing.Processor.prepareDdl(Processor.java:59) ~[polypheny-db.jar:?]
	at org.polypheny.db.webui.Crud.processQuery(Crud.java:3857) ~[polypheny-db.jar:?]
	at org.polypheny.db.webui.Crud.executeSqlUpdate(Crud.java:3886) ~[polypheny-db.jar:?]
	... 43 more
Caused by: io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
```

**Comment by vogti** [comment]
Thanks for reporting this issue. Has been fixed in #384.
