### ISSUE TITLE
Clarify Java version requirements in docs - Crash on Java 19

### ISSUE THREAD

**Issue by danielhass** [polypheny/Polypheny-DB#420]
### Operating System (Polypheny-DB)

Linux

### Polypheny-DB Version

v0.8.0

### Affected Areas

DB, Website

### Browser

Firefox

### Client Operating System

Arch Linux Kernel 6.0.6-arch1-1

### Bug Description

Following the setup guide from here https://github.com/polypheny/Website/blob/master/release.md?plain=1#L26 I tried to run the Polypheny jar with Java 19 (which is greater than 11 and matches the requirements from the website). Sadly this results in an immediate crash.

Switching to Java 11 on my system made Polypheny starting out-of-the-box without any errors.

### Reproduction Steps

Try to run Polypheny jar with Java 19:

```
> java -version
openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment (build 19.0.1+10)
OpenJDK 64-Bit Server VM (build 19.0.1+10, mixed mode)

> java -jar Polypheny-0.8.0.jar
```

### Expected Behavior

Polypheny should either properly support Java 19 or the `Setup` website (and docs overall) should narrow down the supported Java versions more strictly.

### Relevant Log Output

```shell
> java -jar Polypheny-0.8.0.jar
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
12:05:29.147 ERROR [main]: Uncaught Throwable.
 java.lang.NoSuchMethodException: java.util.concurrent.Executors.newVirtualThreadExecutor()
	at java.lang.Class.getMethod(Class.java:2277) ~[?:?]
	at io.javalin.core.LoomUtil.getExecutorService(LoomUtil.kt:22) ~[Polypheny-0.8.0.jar:0.8.0]
	at io.javalin.jetty.LoomThreadPool.<init>(JettyUtil.kt:89) ~[Polypheny-0.8.0.jar:0.8.0]
	at io.javalin.jetty.JettyUtil.defaultThreadPool(JettyUtil.kt:28) ~[Polypheny-0.8.0.jar:0.8.0]
	at io.javalin.jetty.JettyUtil.getOrDefault(JettyUtil.kt:20) ~[Polypheny-0.8.0.jar:0.8.0]
	at io.javalin.jetty.JettyServer.server(JettyServer.kt:34) ~[Polypheny-0.8.0.jar:0.8.0]
	at io.javalin.Javalin.start(Javalin.java:179) ~[Polypheny-0.8.0.jar:0.8.0]
	at io.javalin.Javalin.start(Javalin.java:147) ~[Polypheny-0.8.0.jar:0.8.0]
	at org.polypheny.db.webui.ConfigServer.<init>(ConfigServer.java:65) ~[Polypheny-0.8.0.jar:0.8.0]
	at org.polypheny.db.PolyphenyDb.runPolyphenyDb(PolyphenyDb.java:285) ~[Polypheny-0.8.0.jar:0.8.0]
	at org.polypheny.db.PolyphenyDb.main(PolyphenyDb.java:143) [Polypheny-0.8.0.jar:0.8.0]
12:05:29.153 ERROR [main]: Error: java.util.concurrent.Executors.newVirtualThreadExecutor()
```

**Comment by vogti** [comment]
Thank you, @danielhass, for reporting this. We have fixed support for Java 19 and will shortly release version 0.8.1 including this fix.
